FROM centos:centos8.1.1911

RUN yum clean all && yum makecache && yum install -y gcc make wget pcre pcre-devel openssl openssl-devel  && yum clean all


# /var/lib/
# docker rmi jacarlianda/fastdfs-base:v1 &&docker build -t jacarlianda/fastdfs-base:v1 -f Dockerfile.1 .