# centos 7
FROM centos:centos8.1.1911

# Run
RUN yum clean all && yum makecache && yum install -y gcc make wget pcre pcre-devel openssl openssl-devel \
  && rm -rf /var/cache/yum/* && yum clean all


# /var/lib/
# docker build -t jacarlianda/fastdfs-base:v1 -f Dockerfile.1 .