# centos 7
FROM jacarlianda/fastdfs-base:v1
# 添加配置文件
# add profiles
ADD conf/client.conf /etc/fdfs/
ADD conf/http.conf /etc/fdfs/
ADD conf/mime.types /etc/fdfs/
ADD conf/storage.conf /etc/fdfs/
ADD conf/tracker.conf /etc/fdfs/
ADD fastdfs.sh /home
ADD conf/nginx.conf /etc/fdfs/
ADD conf/mod_fastdfs.conf /etc/fdfs

# 添加源文件
# add package code
ADD package/libfastcommon-master.zip /usr/local/src/
ADD package/fastdfs-master.zip /usr/local/src/
ADD package/fastdfs-nginx-module-master.zip /usr/local/src/
ADD package/nginx-1.16.1.tar.gz /usr/local/src/
ADD package/openssl-1.1.1f.tar.gz /usr/local/src/

# Run
RUN yum install gcc gcc-c++ make automake autoconf libtool pcre pcre-devel zlib zlib-devel openssl-devel vim -y \
  &&  mkdir /home/dfs   \
  &&  cd /usr/local/src/  \
  &&
  &&  cd libfastcommon-master/   \
  &&  ./make.sh && ./make.sh install  \
  &&  cd ../  \
  &&  cd fastdfs-master/   \
  &&  ./make.sh && ./make.sh install  \
  &&  cd ../  \
  &&  cd nginx-1.16.1/  \
  &&  ./configure --add-module=/usr/local/src/fastdfs-nginx-module-master/src/   \
  &&  make && make install  \
  &&  chmod +x /home/fastdfs.sh


# export config
VOLUME /etc/fdfs


EXPOSE 22122 23000 8888 80
ENTRYPOINT ["/home/fastdfs.sh"]